server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
    encoding:
      enabled: true
      charset: UTF-8
      force: true

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: rumor-tracing-backend

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  profiles:
    active: local

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:rumor_tracing}?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&logger=Slf4JLogger&profileSQL=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:Yxh258012}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      leak-detection-threshold: 30000

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1

  elasticsearch:
    rest:
      uris: http://localhost:9200
      username: elastic
      password: yxh258012
    connection-timeout: 5000
    socket-timeout: 5000

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    root: INFO
    com.rumor.tracing: DEBUG
    org.springframework.web: DEBUG
    org.springdoc: DEBUG
    org.springframework.security: INFO
    org.hibernate: DEBUG
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc: DEBUG
  file:
    name: logs/application.log

ai:
  service:
    url: https://api.deepseek.com
    api-key: ${DEEPSEEK_API_KEY:sk-c8c70eeb1e2243bf86eaa3e279549074}
    timeout: 60000
    max-retries: 3
    retry-delay: 1000
    model: deepseek-chat
    temperature: 0.7
    max-tokens: 2000
    frequency-penalty: 0
    presence-penalty: 0
    top-p: 1

jwt:
  secret: ${JWT_SECRET:J8#kL9$mN2@pQ5*rT7&vX3!wY4^zB6}
  expiration: ${JWT_EXPIRATION:86400}

# OpenAPI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  packages-to-scan: com.rumor.tracing.controller
  paths-to-match: /api/**
  group-configs:
    - group: 'default'
      paths-to-match: '/api/**'
      packages-to-scan: com.rumor.tracing.controller

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

