name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Backend - Clean and Compile
      run: |
        cd backend
        mvn clean compile
    
    - name: Backend - Run Tests
      run: |
        cd backend
        mvn test
    
    - name: Frontend - Install Dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Frontend - Build
      run: |
        cd frontend
        npm run build
    
    - name: Frontend - Run Tests
      run: |
        cd frontend
        npm run test
    
    - name: Frontend - Lint Check
      run: |
        cd frontend
        npm run lint 