name: Load Testing

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 2 * * 1'  # 每周一凌晨2点运行

jobs:
  load-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
    
    - name: Start Backend Service
      run: |
        cd backend
        mvn spring-boot:run &
        sleep 60  # 等待服务启动
    
    - name: Install K6
      run: |
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
        echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt-get update
        sudo apt-get install k6
    
    - name: Run Load Tests
      run: |
        cd load-testing
        k6 run --out json=load-test-results.json k6-load-test.js
    
    - name: Upload Load Test Results
      uses: actions/upload-artifact@v3
      with:
        name: load-test-results
        path: load-testing/load-test-results.json
    
    - name: Generate Load Test Report
      run: |
        echo "## 负载测试报告" > load-test-report.md
        echo "" >> load-test-report.md
        echo "测试时间: $(date)" >> load-test-report.md
        echo "" >> load-test-report.md
        echo "详细结果请查看artifacts中的load-test-results.json文件" >> load-test-report.md
    
    - name: Comment PR with Results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const report = fs.readFileSync('load-test-report.md', 'utf8');
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: report
          }); 